version: "3"
services:
  app:
    build: .
    container_name: loja-api
    command: bin/rails server --port 3040 --binding 0.0.0.0
    ports:
    - 3040:3040
    links:
    - db
    volumes:
    - .:/loja-api
    - gems:/gems
    tty: true
    stdin_open: true
  db:
    image: postgres:11
    container_name: loja-api-db
    volumes:
    - database:/var/lib/postgresql/data
    ports:
    - 3041:5432
volumes:
  database:
  gems:
